### ISSUE TITLE
More resources

### ISSUE THREAD

**Issue by LadyAleena** [thibaultduponchelle/perlres#19]
Here are a few more resources you might want to add:

- [Perl jobs](https://jobs.perl.org) ([Twitter](https://twitter.com/perljobs))
- [Raku](https://www.raku.org) ([Twitter](https://twitter.com/raku_lang))
- [Planet Perl Iron Man](http://ironman.enlightenedperl.org/) ([Twitter](https://twitter.com/perlironman))
- Perl on Facebook (the top three searches)
  - [Perl programmers](https://www.facebook.com/groups/perlprogrammers/)
- [Perl on geeksforgeeks](https://www.geeksforgeeks.org/perl-programming-language/)
- [Perl on GitHub](https://github.com/topics/perl) - repos with perl tag
- [Perl on Stack Exchange](https://stackexchange.com/search?q=perl) - unsorted list of questions
- [Perl on Twitter](https://twitter.com/hashtag/Perl) - the hashtag only

# Other social media accounts:

- Perl.org ([Twitter](https://twitter.com/perlorg), [Facebook](https://www.facebook.com/perl-16665510298/))
- Perl Foundation ([Twitter](https://twitter.com/perlfoundation), [Facebook](https://www.facebook.com/tpf.perl))
- Perl Maven ([Twitter](https://twitter.com/PerlMaven))
- Perl School ([Twitter](https://twitter.com/perl_school))
- Perl Shop ([Twitter](https://twitter.com/ThePerlShop))
- Perl Weekly ([Twitter](https://twitter.com/PerlWeekly))
- Perl Weekly Challenge ([Twitter](https://twitter.com/PerlWChallenge))
- Perl Banjo ([Twitter](https://twitter.com/PerlBanjo))
- PerlBuzz ([Twitter](https://twitter.com/perlbuzz))
- Raku ([Twitter](https://twitter.com/raku_lang))
- Conference in a Cloud ([Twitter](https://twitter.com/PerlConferences))
- BuiltinPerl ([Twitter](https://twitter.com/BuiltinPerl))
- Cultured Perl ([Twitter](https://twitter.com/culturedperl))
- Meta::CPAN ([Twitter](https://twitter.com/metacpan))
- irc.perl.org ([Twitter](https://twitter.com/perl_irc))

# Perl Mongers

This is not a comprehensive list.

[Perl Mongers](https://www.pm.org/) ([Twitter](https://twitter.com/perl_mongers), [Facebook group](https://www.facebook.com/groups/perlmonger/))

### North America
- :us: [Ann Arbor](http://annarbor.pm.org/) ([Facebook group](https://www.facebook.com/groups/295369588223/))
- :us: [Atlanta](http://atlanta.pm.org) ([Facebook page](https://www.facebook.com/Atlanta-Perl-Mongers-160970284513))
- :us: [Austin](http://austin.pm/) ([Facebook group](https://www.facebook.com/groups/austinperlmongers/), [GitHub](https://github.com/austin-perl-mongers))
- :us: [Boston](http://boston.pm.org) ([Twitter](https://twitter.com/BostonPM), Facebook: [page](https://www.facebook.com/bostonpm), [group](https://www.facebook.com/groups/131595281237/))
- :us: [Buffalo](http://buffalo.pm.org/) ([Facebook group](https://www.facebook.com/groups/6973281799/))
- :us: Charlotte ([GitHub](https://github.com/charlotte-perl-mongers))
- :us: [Chicago](http://chicago.pm.org/) ([GitHub](https://github.com/ChicagoPM))
- :us: [Los Angeles](http://la.pm.org) (Facebook: [page](https://www.facebook.com/Los-Angeles-Perl-Mongers-110460472327702), [group](https://www.facebook.com/groups/119158178096277/))
- :us: [Philadelphia](https://philadelphia.pm.org/) ([Twitter](https://twitter.com/philapm))
- :us: [Pittsburgh](http://pittsburgh.pm.org) ([Facebook page](https://www.facebook.com/Pittsburgh-Perl-Mongers-134841096610785))
- :us: [Portland](https://pdx.pm.org/) ([Twitter](https://twitter.com/pdxperlmongers), [GitHub](https://github.com/PortlandPerlMongers))
- :us: [Purdue](https://purdue.pl/) ([Twitter](https://twitter.com/PurduePM), [GitHub](https://github.com/Purdue-Perl-Mongers))
- :us: [Salt Lake City](http://slcperlmongers.com/) ([Facebook group](https://www.facebook.com/groups/515481075169254/))
- :us: [San Francisco](http://www.meetup.com/San-Francisco-Perl/) ([Facebook page](https://www.facebook.com/SanFranciscoPerlMongers))
- :canada: Toronto ([Twitter](https://twitter.com/TOperlmongers), [GitHub](https://github.com/toronto-perl-mongers/tpm-website))

### South America

- :peru: [Lima](http://lima.pm.org) ([Facebook page](https://www.facebook.com/limaperlmongers))
- :brazil: [Rio de Janeiro](http://rio.pm.org) ([Facebook page](https://www.facebook.com/RioPerlMongers))

## Asia

- :india: [Bangalore](http://bangalore.pm.org) ([Facebook page](https://www.facebook.com/Perl-Mongers-Bangalore-108723775890980), [GitHub](https://github.com/Bangalore-Perl-Mongers))
- :jp: [Kansai](http://kansai.pm.org) ([Twitter](https://twitter.com/kansaipm), [Facebook page](https://www.facebook.com/kansaipm))
- :malaysia: Malaysia ([Facebook page](https://www.facebook.com/Malaysia-Perl-Mongers-2089797024599831))
- :ru: [Ryazan](http://ryazan.pm.org) ([Facebook page](https://www.facebook.com/ryazan.pm))

## Europe

- :es: [Barcelona](https://barcelona.pm/) ([Twitter](https://twitter.com/barcelonapm), [GitHub](https://github.com/barcelonapm))
- :norway: [Bergen](https://bergenpm.org/) ([Twitter](https://twitter.com/BergenPM))
- :de: [Berlin](https://berlin.pm.org/) ([Twitter](https://twitter.com/BerlinPM))
- :czech_republic: [Brno](http://brno.pm.org) ([Facebook page](https://www.facebook.com/brnopm))
- :romania: [Cluj](http://www.:romancluj.pm/) ([Twitter](https://twitter.com/clujpm), [Facebook page](https://www.facebook.com/clujpm))
- :de:  [Frankfurt](http://fankfurt.pm) ([Facebook page](https://www.facebook.com/frankfurt.pm))
- :de: [Niederrhein](http://niederrhein.pm.org) ([Facebook page](https://www.facebook.com/Niederrhein-Perl-Mongers-176634792354842))
- :norway: [Oslo](http://oslo.pm/) ([Facebook group](https://www.facebook.com/groups/oslo.pm/), [GitHub](https://github.com/oslo-pm))
- :poland: [Poznań](http://poznan.pm.org) ([Facebook page](https://www.facebook.com/poznanpm))
- :austria: [Vienna](http://vienna.pm.org/) ([Twitter](https://twitter.com/ViennaPerl))

## Oceania

- :australia: [Melbourne](https://melbourne.pm.org/) ([Facebook group](https://www.facebook.com/groups/146370755427693/))
- :australia: [Sydney](http://perl.sydney/) ([Facebook page](https://www.facebook.com/sydneypm/))

**Comment by thibaultduponchelle** [comment]
Thank you a lot ! 😃

**Comment by LadyAleena** [comment]
Updated the list with a slew of Perl Monger links.

**Comment by thibaultduponchelle** [comment]
Great ! 👍 😃

**Comment by thibaultduponchelle** [comment]
I think we can close this issue thanks to your pull request that is now merged :)
