### ISSUE TITLE
Incorrect capitalization of company names

### ISSUE THREAD

**Issue by LadyAleena** [thibaultduponchelle/perlres#22]
May I ask why company names are not properly capitalized? Twitter, Facebook, and GitHub are the proper capitalization of those company names, so should be used as such for linking to their respective sites. At least that is how I was taught. Using lowercase is grammatically incorrect.

**Comment by thibaultduponchelle** [comment]
Just a personal preference (for cosmetic in this particular repo), I would obviously respect if it was people names but it's "just" company names :smile:
