### ISSUE TITLE
Resource for HTML/JavaScript scraping 

### ISSUE THREAD

**Issue by Baseband-processor** [thibaultduponchelle/perlres#23]
Hi Tibault,

I was searching for some interesting resources about "WebSite scraping", precisely JS scraping.

In those days I am having some difficulties in a JS scraping work and honestly I haven't any valid resource for understanding how do it.

Regards,

Edoardo Mantovani, 2020

**Comment by thibaultduponchelle** [comment]
Unfortunately, I'm not sure bout what are the resources are.

I could mention LWP, Web::Scaper and Mojolicious but I think (not expert) that they are more "crawler + toolbox" (like css selectors, convert html to Perl structures) than a full web scraping solution.

I'm personnally searching how to do robust web scraping (tolerant to data changes).

What you mean exactly by "JS scraping" ? You're only interested in the javascript code retrieved ?

**Comment by Baseband-processor** [comment]
HI Tibault!

When I refer to JS scrape I intend how to scrape loaded DOM code by JS
function.

Is like the difference between the "inspect page source", which retrieve
only static HTML, and "inspect", which retrieve also JS + DOM  ecc.. code

Regards
Edoardo Mantovani, 2020

Il giorno mer 9 dic 2020 alle ore 16:31 thibaultduponchelle <
notifications@github.com> ha scritto:

**Comment by thibaultduponchelle** [comment]
Hello Edoardo,

I will close this issue since it's more a question than something that can be fixed in this repository.
Do not hesitate to contribute if you finally find these resources. I will happily merge them if I consider them sufficiently well-known and serious :smile:

Best regards.

Thibault
