### ISSUE TITLE
Cowsay and Asciiquarium in Sysadmin category?

### ISSUE THREAD

**Issue by Veraellyunjie** [thibaultduponchelle/perlres#33]
🐮 [Cowsay](https://github.com/tnalpgge/rank-amateur-cowsay) - The cow that can speak
🐠 [Asciiquarium](https://github.com/cmatsuoka/asciiquarium) - An aquarium in your terminal

Both are cool, but hardly sysadmin tools.
Suggesting "Uncategorized" category or maybe a new one

**Comment by thibaultduponchelle** [comment]
I thought it was some "fun for sysadmin" 😄
