### ISSUE TITLE
Add modules for Language Server Protocol (LSP)

### ISSUE THREAD

**Issue by intfwd** [thibaultduponchelle/perlres#34]
Hello. 

Please, add:

Perl Navigator Language Server - https://github.com/bscan/PerlNavigator 
Perl::LanguageServer - Language Server and Debug - https://metacpan.org/pod/Perl::LanguageServer
PLS - Perl Language Server - https://metacpan.org/pod/PLS

It's useful for modern development.

Thanks in advance.

**Comment by thibaultduponchelle** [comment]
Thank you @intfwd 😃 

I will prepare this change 👍🏼

**Comment by thibaultduponchelle** [comment]
@intfwd I did the changes (under IDE).

Thank you for the suggestion! 👍🏼
