### ISSUE TITLE
Add Relianoid load balancer

### ISSUE THREAD

**Issue by josepgl** [thibaultduponchelle/perlres#37]
Hello,

Please add as continuation of Zevenet load balancer:

Relianoid load balancer
https://www.relianoid.com/
https://github.com/relianoid/adc-loadbalancer

Zevenet is discontinued and archived https://github.com/zevenet/zlb

Thanks in advance.

**Comment by thibaultduponchelle** [comment]
Hello @josepgl,

I just added Relianoid as you suggested, thank you! :+1:
